# Generated by Django 2.0.2 on 2019-05-30 06:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_auto_20190530_1130'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='cteate_time',
            new_name='create_time',
        ),
    ]
