# Generated by Django 2.2.1 on 2019-05-31 03:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('product', '0004_auto_20190530_1447'),
    ]

    operations = [
        migrations.CreateModel(
            name='Api_Test_Case',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('apitestname', models.CharField(max_length=64, verbose_name='流程接口名称')),
                ('apitestdesc', models.CharField(max_length=64, verbose_name='描述')),
                ('apitester', models.CharField(max_length=64, verbose_name='测试负责人')),
                ('apitestresult', models.BooleanField(verbose_name='测试结果')),
                ('create_time', models.DateTimeField(auto_now=True, verbose_name='创建时间')),
                ('Product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='product.Product')),
            ],
            options={
                'verbose_name': '流程场景接口',
                'verbose_name_plural': '流程场景接口',
                'db_table': 'api_test_case',
            },
        ),
        migrations.CreateModel(
            name='Api_Test_Step',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('apiname', models.CharField(max_length=64, verbose_name='描述')),
                ('apiurl', models.CharField(max_length=64, verbose_name='测试负责人')),
                ('apistep', models.BooleanField(verbose_name='测试结果')),
                ('apiparamvalue', models.CharField(max_length=64, verbose_name='描述')),
                ('apimethod', models.CharField(max_length=64, verbose_name='测试负责人')),
                ('apiresult', models.CharField(max_length=64, verbose_name='描述')),
                ('apiresponse', models.CharField(max_length=64, verbose_name='测试负责人')),
                ('apistatus', models.CharField(max_length=64, verbose_name='描述')),
                ('create_time', models.DateTimeField(auto_now=True, verbose_name='创建时间')),
                ('Apitest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apitest.Api_Test_Case')),
            ],
        ),
    ]
