# Generated by Django 2.2.1 on 2019-05-31 03:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apitest', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='api_test_step',
            table='api_test_step',
        ),
    ]
