# Generated by Django 2.2.1 on 2019-05-31 05:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apitest', '0003_auto_20190531_1310'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='api_test_step',
            options={'verbose_name': '接口', 'verbose_name_plural': '接口'},
        ),
    ]
